<?php

declare(strict_types=1);

namespace App\Domain\Machine\Services;

use App\Domain\Machine\DataTransferObjects\MachineData;
use App\Domain\Machine\Events\MachineStatusChangedEvent;
use App\Domain\Machine\Exceptions\MachineNotFoundException;
use App\Domain\Machine\Models\Machine;
use App\Domain\Machine\Repositories\Contracts\MachineRepositoryInterface;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;

/**
 * MachineService
 *
 * Business rules for machine lifecycle management.
 *
 * KEY RULE: factory_id is resolved from the auth user at the controller/action
 * level — this service receives it explicitly to remain testable without HTTP.
 */
class MachineService
{
    public function __construct(
        private readonly MachineRepositoryInterface $machines,
    ) {}

    // ── Queries ───────────────────────────────────────────────

    public function list(int $factoryId, array $filters = [], int $perPage = 25): LengthAwarePaginator
    {
        return $this->machines->paginate($factoryId, $filters, $perPage);
    }

    public function findOrFail(int $id): Machine
    {
        return $this->machines->findById($id)
            ?? throw new MachineNotFoundException($id);
    }

    public function allActiveForDropdown(int $factoryId): Collection
    {
        return $this->machines->allActiveByFactory($factoryId);
    }

    public function availableTypes(int $factoryId): Collection
    {
        return $this->machines->distinctTypesByFactory($factoryId);
    }

    // ── Write Operations ──────────────────────────────────────

    /**
     * Create a machine.
     *
     * BUSINESS RULES:
     *   - code must be unique within the factory (composite constraint)
     *   - device_token is generated by the repository; caller gets it via event/return
     */
    public function create(int $factoryId, MachineData $data): Machine
    {
        $this->guardDuplicateCode($factoryId, $data->code);

        return $this->machines->create($factoryId, $data);
    }

    public function update(Machine $machine, MachineData $data): Machine
    {
        $this->guardDuplicateCode($machine->factory_id, $data->code, ignoreId: $machine->id);

        $previousStatus = $machine->status;
        $updated        = $this->machines->update($machine, $data);

        if ($previousStatus !== $updated->status) {
            event(new MachineStatusChangedEvent($updated, $previousStatus, $updated->status));
        }

        return $updated;
    }

    /**
     * Retire a machine.
     *
     * BUSINESS RULE: Cannot retire a machine with an open downtime.
     * Downtime must be resolved before retirement.
     */
    public function retire(Machine $machine): void
    {
        $openDowntime = $machine->activeDowntime()->exists();

        if ($openDowntime) {
            throw new \DomainException(
                "Machine [{$machine->code}] has an open downtime. Close it before retiring."
            );
        }

        $this->machines->retire($machine);

        event(new MachineStatusChangedEvent($machine, $machine->status, 'retired'));
    }

    /**
     * Rotate device token — invalidates existing IoT firmware credential.
     * Returns new plaintext token; must be securely delivered to device.
     */
    public function rotateToken(Machine $machine): string
    {
        return $this->machines->rotateDeviceToken($machine);
    }

    // ── Guards ────────────────────────────────────────────────

    private function guardDuplicateCode(int $factoryId, string $code, ?int $ignoreId = null): void
    {
        if (! $this->machines->isCodeUniqueInFactory($factoryId, $code, $ignoreId)) {
            throw new \DomainException(
                "Machine code [{$code}] already exists in this factory."
            );
        }
    }
}
