<?php

declare(strict_types=1);

namespace App\Domain\Machine\DataTransferObjects;

use App\Http\Requests\Api\Machine\CreateMachineRequest;
use App\Http\Requests\Api\Machine\UpdateMachineRequest;
use Illuminate\Foundation\Http\FormRequest;

/**
 * MachineData — immutable DTO for machine write operations.
 *
 * NOTE: factory_id and device_token are NOT in this DTO.
 *   factory_id  → always set from auth()->user()->factory_id in the action
 *   device_token → generated by CreateMachineAction; never from user input
 */
final readonly class MachineData
{
    public function __construct(
        public string  $name,
        public string  $code,
        public string  $type,
        public ?string $model,
        public ?string $manufacturer,
        public string  $status,
        public ?string $installedAt,
    ) {}

    public static function fromCreateRequest(CreateMachineRequest $request): self
    {
        return new self(
            name:         $request->validated('name'),
            code:         strtoupper(trim($request->validated('code'))),
            type:         $request->validated('type'),
            model:        $request->validated('model'),
            manufacturer: $request->validated('manufacturer'),
            status:       'active',
            installedAt:  $request->validated('installed_at'),
        );
    }

    public static function fromUpdateRequest(UpdateMachineRequest $request): self
    {
        return new self(
            name:         $request->validated('name'),
            code:         strtoupper(trim($request->validated('code'))),
            type:         $request->validated('type'),
            model:        $request->validated('model'),
            manufacturer: $request->validated('manufacturer'),
            status:       $request->validated('status', 'active'),
            installedAt:  $request->validated('installed_at'),
        );
    }

    public function toArray(): array
    {
        return [
            'name'         => $this->name,
            'code'         => $this->code,
            'type'         => $this->type,
            'model'        => $this->model,
            'manufacturer' => $this->manufacturer,
            'status'       => $this->status,
            'installed_at' => $this->installedAt,
        ];
    }
}
